[PHP]
memory_limit = 512M
upload_max_filesize = 64M
post_max_size = 64M
max_execution_time = 120
max_input_vars = 3000

date.timezone = Europe/Moscow

[opcache]
opcache.enable = 1
opcache.memory_consumption = 256
opcache.interned_strings_buffer = 16
opcache.max_accelerated_files = 20000
opcache.revalidate_freq = 60
opcache.validate_timestamps = 0

[Session]
; Laravel uses cookie driver, native PHP sessions are not used.
session.save_handler = files
session.save_path = /tmp
