<?php

namespace App\Http\Controllers\Web;

use App\Http\Controllers\Controller;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;

class E2ECaptchaController extends Controller
{
    /**
     * Return the current captcha code for the session.
     *
     * Only accessible via a signed URL generated by the e2e harness.
     * Used to drive real login/registration tests through the browser.
     */
    public function __invoke(Request $request): JsonResponse
    {
        if (! $request->hasValidSignature()) {
            abort(403, 'Invalid or expired link.');
        }

        $code = session('captcha_code');

        if (! $code) {
            return response()->json(['message' => 'Captcha not generated yet. Call /captcha first.'], 422);
        }

        return response()->json(['code' => $code]);
    }
}
