server {
    listen 80;
    server_name _;
    root /var/www/api/public;
    index index.php;

    location = /admin {
        return 301 /admin/;
    }

    location /api/ {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location /admin/ {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location /storage/ {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ ^/livewire {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location /css/filament/ {
        alias /var/www/api/public/css/filament/;
    }

    location /js/filament/ {
        alias /var/www/api/public/js/filament/;
    }

    location /fonts/filament/ {
        alias /var/www/api/public/fonts/filament/;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass api:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
    }

    location ~ /\.ht {
        deny all;
    }
}
