api:
  dashboard: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false
    network: traefik-public

certificatesResolvers:
  letsencrypt:
    acme:
      email: ${ACME_EMAIL:-admin@example.com}
      storage: /letsencrypt/acme.json
      tlsChallenge: {}
